---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: "greasedscone.uk"
subdomain: "api.%{hiera('deployment_identifier')}"
public_zone_id: "Z4Q2X3ESOZT4N"
