---
configuration_directory: "%{cwd}/spec/unit/infra/prerequisites"
state_file: "%{cwd}/state/prerequisites.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  domain_name: "%{hiera('component')}-%{hiera('deployment_identifier')}.%{hiera('domain_name')}"
  public_zone_id: "%{hiera('public_zone_id')}"
